### ISSUE TITLE
Peer to peer code review (03/03/2023)

### ISSUE THREAD

**Issue by MesakDuduCoder** [Jawad-Nazari/Portfolio-Mobile-1#5]
1. Please try changing font sizes to rem unit instead of px unit to make fonts responsive.
2. Please try to see if changing the height of the text container in projects section to percentages for responsiveness.
3. Please consider using grid layout instead of flex-box layout to make your page more responsive.

**Comment by Jawad-Nazari** [comment]
The suggestions will be considered and applied.
